### PR TITLE
Allow configuration resolution to happen at the configuration phase.

### PR DESCRIPTION
**Pull request by ftclausen**
We have a multi-project build and, for various reasons, the configuration resolution is triggered at the Gradle configuration phase. Whether this is desirable or not is another matter but in order for us to move forward I added an option `-PdependencyLock.lockAtConfigurationPhase=true` that lock the dependencies at the configuration phase.

Without this option we end up pulling down incorrectly versioned artifacts since the dependency configurations are not (yet) locked.

### CODE REVIEW

**Comment by ftclausen** [comment]
@dcow The issue, as I understand it, is that evaluating *after all project's build files have been executed but prior to task execution phase* (aka configuration phase) means that if a dependency configuration resolution is triggered (via [resolvedConfiguration](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:resolvedConfiguration)) during this first evaluation (but prior to task execution) then the lock does not take affect. We do something like the following which is executed at configuration phase prior to task execution phase :  

    def ourArtifacts = configurations.myConfig.resolvedConfiguration.resolvedArtifacts.findAll { 
        it.moduleVersion.id.group.startsWith('com.example')
    }

then use `ourArtifacts` as a list from which to get artifact files for use in, for example, integration tests. Since that list is composed at the configuration phase (not execution phase) the Gradle dependency lock is not yet applied and we get the latest artifacts rather than the ones in the lock file.

This PR allows the above example to use the lock file versions by applying the lock earlier, namely, at the configuration phase. This ensures the actual locked versions are used.

**Comment by dcow** [comment]
Sure, I understand the issue. I was mostly being picky about wording so as to make sure future readers are not confused (=

**Comment by ftclausen** [comment]
Ah, I see what you mean, I'll update the wording to be less confusing

**Comment by ftclausen** [comment]
I've updated the wording in the README - let me know if that's clearer.

**Pull request merged**
